<a href="https://colab.research.google.com/github/tshankar/numpy-practice/blob/main/professor_prick.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Professor Prick](https://www.practiceprobs.com/problemsets/python-numpy/intermediate/professor-prick/)

You’re a vindictive professor 👨‍🏫 and one of your pet peeves is when students rush through their exams. To teach them a lesson, you decide to give zeros to the first three students who score less than sixty, in the order they turned in their exams.

Given a 1-d array of integers, identify the first three values less than sixty and replace them with zero.

In [1]:
import numpy as np

generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30, high=100, size=15))

print(scores)
# [68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


---

In [2]:
# Your brilliant solution here!
# Get indices of all scores < 60

mask = scores < 60 #  array with True values where mask is true
bad_students = np.where(mask)[0]
scores[bad_students[:3]] = 0

scores

array([68.,  0., 76.,  0.,  0., 54., 63., 64., 36., 88., 80., 82., 84.,
       76., 42.])

## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/intermediate/professor-prick/solution/)