<a href="https://colab.research.google.com/github/tshankar/numpy-practice/blob/main/psycho_parent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Pyscho Parent](https://www.practiceprobs.com/problemsets/python-numpy/intermediate/psycho-parent/)

Eager to make your mark on the PTA, you decide the best way to hide eggs for the upcoming Easter egg hunt is to use NumPy . You represent the field as a 10x10 array of 0s.

In [1]:
import numpy as np

field = np.zeros(shape = (10, 10))

print(field)
# [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Insert 20 random normal values at random (non repeating) locations in the grid. Then you'll know how much candy to hide at each spot.

---

In [14]:
# Your brilliant solution here!

# Get 20 random normal values in an array
vals = np.random.randn(20)

# Get 20 random numbers between 1 and 100 non repeating
locs = np.random.choice(np.arange(100), size=20, replace=False, p=None) # Array of shape (20,)
field = field.reshape(1, -1) # Array of shape (1, 100)

# This says "Look at row 0 and set the values in the columns specified by the numbers in locs".
# We need this because field is a two dimensional array, where all the elements are in row 0
field[0, locs] = vals
field = field.reshape(10, 10)
field

array([[ 0.93151071,  0.        ,  0.5680783 ,  0.        ,  0.12450238,
         0.69456214,  0.        , -2.44608725,  1.63179688,  0.24936591],
       [ 1.32345993,  0.        ,  0.        ,  0.92522712,  0.        ,
         0.        ,  0.        , -0.01226578,  0.        ,  0.58168681],
       [ 0.        ,  2.49857089,  0.        , -1.10677138, -0.50980748,
        -2.88477052,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.25584222, -0.2546681 ,
         0.        , -1.09528028,  0.        ,  0.        ,  1.50461813],
       [-0.66539701,  0.15585237,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.37684106,  1.16149305,  1.006292  ],
       [ 0.        , -0.34041755,  0.29506869, -0.10127136,  1.50846907,
        -0.40112182,  0.98896097,  0.055799  ,  0.        , -0.3223298 ],
       [-0.0712444 ,  0.        ,  1.95287944, -0.216158  ,  1.58828835,
         0.30473777,  0.36434626, -0.57937293

## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/intermediate/psycho-parent/solution/)

In [16]:
field.ravel().shape

(100,)

In [17]:
# Their solution
vals = np.random.randn(20)
locs = np.random.choice(np.arange(100), size=20, replace=False, p=None)
field.ravel()[locs] = vals # ravel flattens input array and returns a view of it, so you can set values and the underlying object will still be modified
field

array([[ 0.93151071,  0.        ,  0.5680783 ,  0.        ,  0.30876366,
         0.69456214,  0.        , -2.44608725, -0.94585653,  0.24936591],
       [ 1.32345993,  1.06489887,  0.        ,  0.92522712,  1.55744627,
         0.        ,  0.        , -0.01226578,  0.85179737,  0.58168681],
       [ 0.        ,  2.49857089,  0.        ,  0.32368401, -0.50980748,
        -2.88477052,  0.0334835 , -0.64017124,  0.        ,  0.        ],
       [ 0.05374018,  0.        ,  1.25300026, -0.25584222, -0.2546681 ,
         0.        , -1.09528028,  0.        ,  0.        ,  1.50461813],
       [-0.66539701,  0.15585237,  0.        ,  0.        ,  0.        ,
         0.38713284, -1.27778988, -0.37684106,  1.16149305,  1.006292  ],
       [ 0.        , -0.34041755,  0.29506869, -0.10127136,  1.50846907,
        -0.40112182,  0.98896097,  0.055799  ,  0.        , -0.3223298 ],
       [-0.0712444 ,  0.        ,  1.95287944, -0.216158  ,  0.87011561,
        -0.75921839,  0.36434626, -0.57937293