<a href="https://colab.research.google.com/github/tshankar/numpy-practice/blob/main/roux.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Roux](https://www.practiceprobs.com/problemsets/python-numpy/beginner/roux/)

Define a *roux* array as a 1-D array such that, when it's reversed, it represents the sequence of square numbers 1, 4, 9, 16, ... with 0s interwoven between them.

**Examples**  

```
# roux array of length 5
[9 0 4 0 1]
```

```
# roux array of length 8
[ 0 16  0  9  0  4  0  1]
```

```
# roux array of length 12
[ 0 36  0 25  0 16  0  9  0  4  0  1]
```

**Note**: odd-length arrays begin with a square number while even-length arrays begin with a zero.

Implement a function called `make_roux(n)` that inputs `n`, the desired size of the array, and outputs the corresponding roux array. Then test it on the examples above.

---

In [6]:
import numpy as np
def make_roux(n):
    """returns a roux array of length n"""

    roux = np.zeros(n)
    num_squares = n // 2 + 1 if n % 2 != 0 else n // 2
    squares = [i ** 2 for i in range(1, num_squares + 1)]
    square_indices = [i for i in range(0, n, 2)]
    roux[square_indices] = squares

    return roux[::-1]


## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/beginner/roux/solution/)